### Coding a Single Neuron

In [1]:
# Inputs to the neuron
inputs = [1, 2, 3]

# Weights associated with each input
weights = [0.2, 0.8, -0.5]

# Bias term added to the weighted sum
bias = 2

# Calculate the output of the neuron using the formula:
# output = (input1 * weight1) + (input2 * weight2) + (input3 * weight3) + bias
output = inputs[0] * weights[0] + inputs[1] * weights[1] + inputs[2] * weights[2] + bias

# Print the output
print(output)


2.3


### Coding a layer

In [2]:
# Inputs to the neurons
inputs = [1, 2, 3, 2.5]

# Weights for the first neuron
weights1 = [0.2, 0.8, -0.5, 1]

# Weights for the second neuron
weights2 = [0.5, -0.91, 0.26, -0.5]

# Weights for the third neuron
weights3 = [-0.26, 0.27, 0.17, 0.87]

# Bias for the first neuron
bias1 = 2

# Bias for the second neuron
bias2 = 3

# Bias for the third neuron
bias3 = 0.5

# Calculate the output of each neuron using the formula:
# output = (input1 * weight1) + (input2 * weight2) + (input3 * weight3) + (input4 * weight4) + bias
output = [
    #neuron1
    inputs[0] * weights1[0] + inputs[1] * weights1[1] + inputs[2] * weights1[2] + inputs[3] * weights1[3] + bias1,
    #neuron2
    inputs[0] * weights2[0] + inputs[1] * weights2[1] + inputs[2] * weights2[2] + inputs[3] * weights2[3] + bias2,
    #neuron3
    inputs[0] * weights3[0] + inputs[1] * weights3[1] + inputs[2] * weights3[2] + inputs[3] * weights3[3] + bias3
]

# Print the output
print(output)


[4.8, 1.21, 3.465]


In [3]:
inputs = [1, 2, 3, 2.5]
weights = [[0.2, 0.8, -0.5, 1], [0.5, -0.91, 0.26, -0.5], [-0.26, 0.27, 0.17, 0.87]]
biases=[2,3,0.5]

# Initialize a list to store the outputs of each neuron
layer_outputs = []

# Calculate the output for each neuron
for neuron_weights, neuron_bias in zip(weights, biases):
    neuron_output = 0
    # Calculate the weighted sum for the current neuron
    for n_input, weight in zip(inputs, neuron_weights):
        neuron_output += n_input * weight
    # Add the bias term
    neuron_output += neuron_bias
    # Append the result to the list of layer outputs
    layer_outputs.append(neuron_output)

# Print the outputs of the layer
print(layer_outputs)


[4.8, 1.21, 3.465]


### A single neuron with numpy

In [4]:
import numpy as np
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

# Calculate the output using NumPy's dot product function
# np.dot(inputs, weights) calculates the weighted sum of inputs
# Adding the bias to the weighted sum
output = np.dot(weights,inputs) + bias

# Print the output
print(output)


4.8


### A layer of neurons with numpy

In [5]:
import numpy as np
inputs = [1, 3, 4, 5]
weights = [
    [0.1, -0.3, 0.4, 0.5],  # Weights for the first neuron
    [0.3, 0.2, -0.9, 1.5],  # Weights for the second neuron
    [0.19, 0.23, 0.14, -0.05]  # Weights for the third neuron
]

biases = [2, 3, 1]

# Calculate the output for each neuron using NumPy
# np.dot(weights, inputs) calculates the weighted sum for each neuron
# biases is added to the corresponding weighted sum for each neuron
output = np.dot(weights, inputs) + biases

# Print the output
print(output)


[5.3  7.8  2.19]


### A layer of neurons & batch of data with numpy

In [6]:
import numpy as np
inputs = [
    [1, 3, 4, 5],          # Example 1
    [3.0, 4.0, -0.9, 2.0], # Example 2
    [-1.7, 2.9, 3.5, -0.9] # Example 3
]
weights = [
    [0.1, -0.3, 0.4, 0.5],  # Weights for the first neuron
    [0.3, 0.2, -0.9, 1.5],  # Weights for the second neuron
    [0.19, 0.23, 0.14, -0.05]  # Weights for the third neuron
]
biases = [2, 3, 1]

# Calculate the output for each example in the batch
# np.array(weights).T transposes the weights matrix to align with the inputs
# np.dot(inputs, np.array(weights).T) computes the dot product between inputs and transposed weights
# biases is added to the corresponding weighted sum for each neuron
output = np.dot(inputs, np.array(weights).T) + biases

# Print the output
print(output)


[[ 5.3    7.8    2.19 ]
 [ 1.74   8.51   2.264]
 [ 1.91  -1.43   1.879]]


### Adding Layers

In [7]:
import numpy as np
inputs = [
    [1, 3, 4, 5],          # Example 1
    [3.0, 4.0, -0.9, 2.0], # Example 2
    [-1.7, 2.9, 3.5, -0.9] # Example 3
]

# Weights for the first layer of neurons
weights1 = [
    [0.1, -0.3, 0.4, 0.5],  # Weights for the first neuron in layer 1
    [0.3, 0.2, -0.9, 1.5],  # Weights for the second neuron in layer 1
    [0.19, 0.23, 0.14, -0.05]  # Weights for the third neuron in layer 1
]

# Biases for the first layer of neurons
biases1 = [2, 3, 1]

# Weights for the second layer of neurons
weights2 = [
    [0.3, -0.1, 0.4],  # Weights for the first neuron in layer 2
    [-0.6, 0.1, -0.4], # Weights for the second neuron in layer 2
    [-0.5, 0.73, -0.14]  # Weights for the third neuron in layer 2
]

# Biases for the second layer of neurons
biases2 = [-2, 1, 0.5]

# Calculate the output of the first layer
# np.dot(inputs, np.array(weights1).T) calculates the weighted sum for each neuron in layer 1
# biases1 is added to the corresponding weighted sum for each neuron in layer 1
layer1_outputs = np.dot(inputs, np.array(weights1).T) + biases1

# Calculate the output of the second layer
# np.dot(layer1_outputs, np.array(weights2).T) calculates the weighted sum for each neuron in layer 2
# biases2 is added to the corresponding weighted sum for each neuron in layer 2
layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2

# Print the output of the second layer
print(layer2_outputs)


[[-0.314   -2.276    3.2374 ]
 [-1.4234  -0.0986   5.52534]
 [-0.5324  -1.0406  -1.76196]]


### Dense Layer Class

In [8]:
import numpy as np

# Input data
X = [
    [1, 3, 4, 5],          # Example 1
    [3.0, 4.0, -0.9, 2.0], # Example 2
    [-1.7, 2.9, 3.5, -0.9] # Example 3
]

# Set the random seed for reproducibility
np.random.seed(0)

# Define the Layer_Dense class
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        # Initialize weights with small random values
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        # Initialize biases as zeros
        self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs):
        # Compute the output of the layer
        self.output = np.dot(inputs, self.weights) + self.biases

# Create instances of Layer_Dense
layer1 = Layer_Dense(4, 6)  # Layer with 4 inputs and 6 neurons
layer2 = Layer_Dense(6, 1)  # Layer with 6 inputs and 1 neuron

# Perform forward pass through layer 1
layer1.forward(X)
print("Output of layer 1")
print(layer1.output)

# Perform forward pass through layer 2
layer2.forward(layer1.output)
print("Output of layer 2")
print(layer2.output)


Output of layer 1
[[ 0.9223807  -0.3837693  -1.03204147  0.8075479   1.2598186  -0.11459155]
 [ 0.90337122 -0.12226562 -0.2982118   0.93720039  0.65630495  0.15855728]
 [ 0.21382385  0.00753456  0.18880229 -0.20391794  0.1694162   0.58286602]]
Output of layer 2
[[0.42159818]
 [0.32781235]
 [0.16372961]]


### Hidden Layer Activation Functions

In [9]:
import nnfs
from nnfs.datasets import spiral_data
import numpy as np

# Initialize the nnfs library
nnfs.init()

# Generate dataset
X, y = spiral_data(100, 3)

# Define the Layer_Dense class
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        # Initialize weights with small random values
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        # Initialize biases as zeros
        self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs):
        # Compute the output of the layer
        self.output = np.dot(inputs, self.weights) + self.biases

# Define the Activation_Relu class
class Activation_Relu:
    def forward(self, inputs):
        # Apply ReLU activation function
        self.output = np.maximum(0, inputs)

# Create instances of Layer_Dense and Activation_Relu
layer1 = Layer_Dense(2, 6)  # Layer with 2 inputs and 6 neurons
activation1 = Activation_Relu()

# Perform forward pass through the layer and activation
layer1.forward(X)
activation1.forward(layer1.output)

# Print the output of the ReLU activation
print(activation1.output)


[[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 6.3385908e-04 0.0000000e+00 7.0642207e-05
  9.0164586e-04]
 [0.0000000e+00 3.9957227e-05 9.2750194e-04 0.0000000e+00 6.5028836e-04
  1.0838244e-03]
 ...
 [9.2587270e-02 0.0000000e+00 2.7677365e-02 6.0882296e-02 0.0000000e+00
  6.9344796e-02]
 [1.4715683e-01 0.0000000e+00 1.5908248e-03 6.8911701e-02 0.0000000e+00
  2.9615715e-02]
 [7.8694962e-02 0.0000000e+00 3.4270126e-02 5.8806412e-02 0.0000000e+00
  7.9367116e-02]]


### Softmax Activation

In [10]:
import nnfs
import numpy as np

# Initialize the nnfs library
nnfs.init()

# Example layer outputs
layer_outputs = [4.8, 1.21, 2.385]

# Compute the exponential values of the layer outputs
exp_values = np.exp(layer_outputs)
print("Exponentiated values:")
print(exp_values)

# Normalize the exponential values to get probabilities (softmax)
norm_values = exp_values / np.sum(exp_values)
print("Normalized values (softmax probabilities):")
print(norm_values)

# Check that the sum of the normalized values is 1
print("Sum of normalized values:")
print(np.sum(norm_values))


Exponentiated values:
[121.51041752   3.35348465  10.85906266]
Normalized values (softmax probabilities):
[0.89528266 0.02470831 0.08000903]
Sum of normalized values:
0.9999999999999999


In [11]:
import nnfs
import numpy as np

# Initialize the nnfs library
nnfs.init()

# Example layer outputs for multiple samples
layer_outputs = [
    [4.8, 1.21, 2.385],  # Sample 1
    [8.9, -1.81, 0.2],   # Sample 2
    [1.41, 1.051, 0.026] # Sample 3
]

# Compute the exponential values for each element in the layer outputs
exp_values = np.exp(layer_outputs)

# Normalize the exponential values to get probabilities (softmax) for each sample
# axis=1 ensures normalization across each row (i.e., each sample)
# keepdims=True ensures that the output has the same number of dimensions as the input
norm_values = exp_values / np.sum(exp_values, axis=1, keepdims=True)

# Print the normalized values
print("Normalized values (softmax probabilities):")
print(norm_values)


Normalized values (softmax probabilities):
[[8.95282664e-01 2.47083068e-02 8.00090293e-02]
 [9.99811129e-01 2.23163963e-05 1.66554348e-04]
 [5.13097164e-01 3.58333899e-01 1.28568936e-01]]


In [12]:
import nnfs
import numpy as np
from nnfs.datasets import spiral_data

# Initialize the nnfs library
nnfs.init()

# Define the Layer_Dense class
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        # Initialize weights with small random values
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        # Initialize biases as zeros
        self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs):
        # Compute the output of the layer
        self.output = np.dot(inputs, self.weights) + self.biases

# Define the Activation_Relu class
class Activation_Relu:
    def forward(self, inputs):
        # Apply ReLU activation function
        self.output = np.maximum(0, inputs)

# Define the Activation_Softmax class
class Activation_Softmax:
    def forward(self, inputs):
        # Compute softmax activation
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities

# Generate dataset
X, y = spiral_data(samples=100, classes=3)

# Create instances of layers and activation functions
dense1 = Layer_Dense(2, 3)       # Dense layer with 2 inputs and 3 neurons
activation1 = Activation_Relu()   # ReLU activation function
dense2 = Layer_Dense(3, 3)       # Dense layer with 3 inputs and 3 neurons
activation2 = Activation_Softmax()  # Softmax activation function

# Perform forward pass through the network
dense1.forward(X)              # Forward pass through the first dense layer
activation1.forward(dense1.output)  # Forward pass through the ReLU activation
dense2.forward(activation1.output)  # Forward pass through the second dense layer
activation2.forward(dense2.output)  # Forward pass through the Softmax activation

# Print the output of the Softmax activation
print(activation2.output)


[[0.33333334 0.33333334 0.33333334]
 [0.33331734 0.3333183  0.33336434]
 [0.3332888  0.33329153 0.33341965]
 [0.33325943 0.33326396 0.33347666]
 [0.33323312 0.33323926 0.33352762]
 [0.33328417 0.33328718 0.33342862]
 [0.33318216 0.33319145 0.33362636]
 [0.33318278 0.33319202 0.33362517]
 [0.33314922 0.33316055 0.3336902 ]
 [0.3331059  0.33311984 0.3337743 ]
 [0.3330813  0.3330968  0.33382186]
 [0.33311027 0.33312503 0.33376473]
 [0.3330537  0.33307084 0.33387548]
 [0.33300948 0.33302936 0.3339612 ]
 [0.33301342 0.33303303 0.33395353]
 [0.33299845 0.333019   0.3339825 ]
 [0.33312678 0.33318865 0.3336846 ]
 [0.3329409  0.33296496 0.33409408]
 [0.33299428 0.33303145 0.33397427]
 [0.3328737  0.33290187 0.33422446]
 [0.3328757  0.33290377 0.33422053]
 [0.33309552 0.33318356 0.33372095]
 [0.33317605 0.33328283 0.3335411 ]
 [0.332894   0.33293876 0.33416727]
 [0.3325638  0.33270204 0.3347342 ]
 [0.33281362 0.33284548 0.3343409 ]
 [0.33314455 0.33327034 0.33358508]
 [0.3331285  0.333258   0.33

### Calculating Loss and Categorical Cross-Entropy loss

In [13]:
import math

# Softmax output probabilities
softmax_output = [0.7, 0.1, 0.2]

# Target output (one-hot encoded)
target_output = [1, 0, 0]

# Compute the cross-entropy loss
loss = -(math.log(softmax_output[0]) * target_output[0] +
         math.log(softmax_output[1]) * target_output[1] +
         math.log(softmax_output[2]) * target_output[2])

print("Cross-entropy loss:")
print(loss)


Cross-entropy loss:
0.35667494393873245


### Implementing Loss

In [14]:
import numpy as np

# Softmax output probabilities for multiple samples
softmax_output = np.array([
    [0.0, 0.1, 0.2],   # Probabilities for sample 1
    [0.1, 0.5, 0.4],   # Probabilities for sample 2
    [0.02, 0.9, 0.08]  # Probabilities for sample 3
])

# True class labels for each sample (0-based index)
class_targets = np.array([0, 1, 1])

# Compute the cross-entropy loss
# Select the probabilities corresponding to the true class labels
# Apply the negative log transformation and calculate the mean loss
loss = np.mean(-np.log(softmax_output[np.arange(len(class_targets)), class_targets]))

print("Cross-entropy loss:")
print(loss)


Cross-entropy loss:
inf


C:\Users\ishaa\AppData\Local\Temp\ipykernel_7080\2826406926.py:16: RuntimeWarning: divide by zero encountered in log
  loss = np.mean(-np.log(softmax_output[np.arange(len(class_targets)), class_targets]))


In [15]:
import nnfs
import numpy as np
from nnfs.datasets import spiral_data

# Initialize the nnfs library
nnfs.init()

# Define the Dense Layer class
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        # Initialize weights with small random values
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        # Initialize biases as zeros
        self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs):
        # Compute the output of the layer
        self.output = np.dot(inputs, self.weights) + self.biases

# Define the ReLU Activation class
class Activation_Relu:
    def forward(self, inputs):
        # Apply ReLU activation function
        self.output = np.maximum(0, inputs)

# Define the Softmax Activation class
class Activation_Softmax:
    def forward(self, inputs):
        # Compute softmax activation
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities

# Define the Loss base class
class Loss:
    def calculate(self, output, y):
        # Calculate the loss value
        sample_losses = self.forward(output, y)
        data_loss = np.mean(sample_losses)
        return data_loss

# Define the Categorical Cross-Entropy Loss class
class Loss_CategoricalCrossentropy(Loss):
    def forward(self, y_pred, y_true):
        samples = len(y_pred)
        # Clip predictions to avoid log(0)
        y_pred_clipped = np.clip(y_pred, 1e-7, 1 - 1e-7)
        if len(y_true.shape) == 1:
            # If y_true is a vector of class indices
            correct_confidences = y_pred_clipped[np.arange(samples), y_true]
        elif len(y_true.shape) == 2:
            # If y_true is a one-hot encoded matrix
            correct_confidences = np.sum(y_pred_clipped * y_true, axis=1)
        # Compute negative log likelihoods
        negative_log_likelihoods = -np.log(correct_confidences)
        return negative_log_likelihoods

# Generate dataset
X, y = spiral_data(samples=100, classes=3)

# Create instances of layers and activation functions
dense1 = Layer_Dense(2, 3)           # Dense layer with 2 inputs and 3 neurons
activation1 = Activation_Relu()      # ReLU activation function
dense2 = Layer_Dense(3, 3)           # Dense layer with 3 inputs and 3 neurons
activation2 = Activation_Softmax()   # Softmax activation function

# Perform forward pass through the network
dense1.forward(X)              # Forward pass through the first dense layer
activation1.forward(dense1.output)  # Forward pass through the ReLU activation
dense2.forward(activation1.output)  # Forward pass through the second dense layer
activation2.forward(dense2.output)  # Forward pass through the Softmax activation

# Print the output of the Softmax activation
print("Softmax output:")
print(activation2.output)

# Calculate the loss using categorical cross-entropy
loss_function = Loss_CategoricalCrossentropy()
loss = loss_function.calculate(activation2.output, y)
print("Categorical Cross-Entropy Loss:")
print(loss)


Softmax output:
[[0.33333334 0.33333334 0.33333334]
 [0.33331734 0.3333183  0.33336434]
 [0.3332888  0.33329153 0.33341965]
 [0.33325943 0.33326396 0.33347666]
 [0.33323312 0.33323926 0.33352762]
 [0.33328417 0.33328718 0.33342862]
 [0.33318216 0.33319145 0.33362636]
 [0.33318278 0.33319202 0.33362517]
 [0.33314922 0.33316055 0.3336902 ]
 [0.3331059  0.33311984 0.3337743 ]
 [0.3330813  0.3330968  0.33382186]
 [0.33311027 0.33312503 0.33376473]
 [0.3330537  0.33307084 0.33387548]
 [0.33300948 0.33302936 0.3339612 ]
 [0.33301342 0.33303303 0.33395353]
 [0.33299845 0.333019   0.3339825 ]
 [0.33312678 0.33318865 0.3336846 ]
 [0.3329409  0.33296496 0.33409408]
 [0.33299428 0.33303145 0.33397427]
 [0.3328737  0.33290187 0.33422446]
 [0.3328757  0.33290377 0.33422053]
 [0.33309552 0.33318356 0.33372095]
 [0.33317605 0.33328283 0.3335411 ]
 [0.332894   0.33293876 0.33416727]
 [0.3325638  0.33270204 0.3347342 ]
 [0.33281362 0.33284548 0.3343409 ]
 [0.33314455 0.33327034 0.33358508]
 [0.3331285 

### Accuracy Calculation

In [16]:
#probabilities of 3 samples
softmax_outputs=np.array([[0.7,0.2,0.1],
                          [0.5,0.1,0.4],
                          [0.02,0.9,0.08]])
#Target (ground-truth) labels for 3 samples
class_targets=np.array([[0,1,1]])

#calculate values along second axis (axis of index 1)
predictions = np.argmax(softmax_outputs,axis=1)

#if targets are one-hot encoded - convert them
if len(class_targets.shape)==2:
    class_targets=np.argmax(class_targets,axis=1)

#True evaluates to 1; Flase to 0
accuracy=np.mean(predictions==class_targets)
accuracy

0.3333333333333333

In [17]:
#Calculate accuracy from output of activation2 and targets
#Calculate values along first axis
predictions =np.argmax(activation2.output,axis=1)
if len(y.shape)==2:
    y=np.argmax(y,axis=1)
accuracy=np.mean(predictions==y)
accuracy

0.34